[package]
authors = ["The Knurling-rs developers"]
categories = ["embedded", "no-std"]
description = "A defmt log sink for custom transports."
edition = "2018"
keywords = ["knurling", "defmt", "defmt-transport"]
license = "MIT OR Apache-2.0"
name = "defmt-buffer"
readme = "README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.2.0"

[dependencies]
cortex-m = "0.7.2"
defmt = { path = "../..", version = "0.2.0" }
bbqueue = { version = "0.4.12" }

[features]
thumbv6 = ["bbqueue/thumbv6"]
