[package]
authors = ["The Knurling-rs developers"]
categories = ["embedded", "no-std"]
description = "A test harness for embedded devices"
edition = "2018"
keywords = ["knurling", "defmt", "testing"]
license = "MIT OR Apache-2.0"
name = "defmt-test"
readme = "README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.2.1"

[dependencies]
cortex-m = "0.7.1"
cortex-m-rt = "0.6.13"
defmt = { version = "0.2.0", path = "../.." }
defmt-test-macros = { version = "=0.2.0", path = "macros" }

[features]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
default = ["defmt-trace"] # enable everything
